language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  # Tricks to avoid unnecessary cache updates
  # http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete